# Generated by Django 3.2.2 on 2021-08-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmeet', '0004_auto_20210811_1907'),
        ('groupmeet', '0004_auto_20210811_2041'),
    ]

    operations = [
    ]
